[package]
name = "camera_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gphoto2 = "1.3.0" # TODO Use the crates version when its published
