[package]
name = "gcam"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
camera_controller = { path = "crates/camera_controller" }
gphoto2 = { git = "https://git.maxicarlos.de/maxicarlos08/gphoto2-rs" }
